# Pytorch - Numpy Learning
## Torch 
<hr/>

In [5]:
# libraries

import torch
import numpy as np 


In [6]:
# numpy 

zeros  = np.zeros((4, 4))
print(zeros)
print()
ones   = np.ones((4, 4))
print(ones)
print()
random = np.random.random((4, 4))
print(random)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[0.14887185 0.95428828 0.59857653 0.55084052]
 [0.60630747 0.50475587 0.31937092 0.91098533]
 [0.77664692 0.35098037 0.60243575 0.66483577]
 [0.38545354 0.19234342 0.99574159 0.47441368]]


In [8]:
# Pytorch

zeros  = torch.zeros(4, 4)
print(zeros)
print()
ones   = torch.ones(4, 4)
print(ones)
print()
random = torch.rand(4, 4)
print(random)


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

tensor([[0.4890, 0.9963, 0.9758, 0.7537],
        [0.5785, 0.6230, 0.0869, 0.4775],
        [0.9793, 0.6736, 0.9017, 0.1821],
        [0.5539, 0.7993, 0.8924, 0.5812]])


# Play 

In [10]:
tensor = torch.rand(4, 4)
tensor

tensor([[0.4165, 0.7103, 0.1388, 0.9000],
        [0.1043, 0.8800, 0.2302, 0.7211],
        [0.7789, 0.1815, 0.1703, 0.9412],
        [0.5113, 0.1861, 0.5624, 0.2353]])

In [38]:
tensor = torch.tensor([[3,5],[9,6]])
tensor

tensor([[3, 5],
        [9, 6]])

In [24]:
# create an arary 

arrayB = np.array([[ 3 , 5 ], [9, 6]])
arrayB

array([[3, 5],
       [9, 6]])

In [42]:
81 / (3 * 9)

3.0

In [44]:
54 / 6

9.0

In [49]:
30

42

In [ ]:
         
  

      [3, 5]   [3, 9]T  =  
      [9, 6]   [5, 6]


In [53]:
arrayB 

array([[3, 5],
       [9, 6]])

# Matrix multiplication  - recreate in 3D graphic - 

In [52]:
#Matrix multiplication  - recreate in 3D graphic - 

arrayB @ arrayB.T

array([[ 34,  57],
       [ 57, 117]])

In [48]:
# elemnt wise

arrayB * arrayB

array([[ 9, 25],
       [81, 36]])

In [54]:

# Revisit numpy ladder challenge  - > apply to torch.  -> Watch Linear Regression


In [145]:
torchA = torch.tensor([[1, 2,],[ 3, 4]]) 
torchB = torch.tensor([[11,12],[13, 14]])

tensorA = torch.tensor([[1, 2,],[ 3, 4]]) 
tensorB = torch.tensor([[11,12],[13, 14]])

In [ ]:
a = torch.tensor([3,5]) 
b = torch.tensor([9,6])

In [106]:
m = torch.tensor([7,5,8]) 
j = torch.tensor([3,9,6])

In [61]:
torchA

tensor([[1, 2],
        [3, 4]])

In [62]:
torchB

tensor([[11, 12],
        [13, 14]])

In [101]:
torchA @ torchB

tensor([[37, 40],
        [85, 92]])

In [68]:
3*4 + 1 *2

14

In [ ]:
[1, 2]    [11, 12]                      [11, 13] T
[3, 4]    [13, 14]                      [12, 14] 

In [ ]:
x1, y1    m1, j1
x2, y2    m2, j2    = 

In [69]:
torchB.shape

torch.Size([2, 2])

In [70]:
torchB.size()

torch.Size([2, 2])

In [72]:
torchB.dim()

2

In [103]:
a

tensor([3, 5])

In [104]:
b

tensor([9, 6])

##  dot product =  Scalor Product  

In [115]:
print(m)
j

tensor([7, 5, 8])


tensor([3, 9, 6])

In [118]:
m @ j

tensor(114)

In [ ]:

[x1, y1] [x2, y2] =   (x1 * x2) + (y1 * y1) 
                         3 * 9 + 5 * 6
                               57

In [110]:
m @ j #  [x1, y1, z1] * [x1, y1, z1]

tensor(114)

In [ ]:
"""

what does the dot product represent in light?

dot =  a "scalar"  not a vector

|a| × |b| × cos(θ) = |a| × cos(θ) × |b|

cos(90) = 0


OR


But what is |a|:
|a| = √(4^2 + 8^2 + 10^2) 

hypotenuse 


"""

In [111]:
#  DOT product :: 
#                   a · b = |a| × |b| × cos(θ) 
   a
#                   a · b = ax × bx + ay × by


a @ b # dot product 

tensor(57)

## cross product = Vector product 

In [117]:
m * j

tensor([21, 45, 48])

In [ ]:
"""
a × b = |a| |b| sin(θ) n


    cx = aybz − azby
    cy = azbx − axbz
    cz = axby − aybx	

"""

---

In [130]:
arrayB

array([[3, 5],
       [9, 6]])

In [127]:
arrayC =  np.array( [[1,1,1],[2,2,2]] )
arrayC

array([[1, 1, 1],
       [2, 2, 2]])

In [140]:
arrayD = arrayB @ arrayC
arrayD

array([[13, 13, 13],
       [21, 21, 21]])

In [137]:
# Dot product 

"""

[3, 5]       [1  [2
[9, 6]        1   2
              1], 2]
              
          
"""

'\n\n[3, 5]   [1  [2\n[9, 6]    1   2\n          1], 2]\n'

In [ ]:
# shape 

In [31]:
# shape and dimentions 

num_dim = array.ndim
num_dim

2

In [33]:
shape = array.shape 
shape

(2, 2)

In [75]:
arrayB

array([[3, 5],
       [9, 6]])

In [83]:
arrayB.reshape((2,2))

array([[3, 5],
       [9, 6]])

In [86]:
torchB.view((2,2))

tensor([[11, 12],
        [13, 14]])

## Determinant

In [ ]:
# -0-0-0-0-0- 

In [90]:
np.linalg.det(arrayB)

-27.0

## Inverse and moore-pensore inverse

In [91]:
# inverse

np.linalg.inv(arrayB)

array([[-0.22222222,  0.18518519],
       [ 0.33333333, -0.11111111]])

In [92]:
# moore Pensore inverse

np.linalg.pinv(arrayB)

array([[-0.22222222,  0.18518519],
       [ 0.33333333, -0.11111111]])

In [150]:
#Inverse and Moore-Pensore inverse


# Inverse
print(np.linalg.inv(array))
print()


# Moore Pensore inverse
np.linalg.pinv(array)



[[-0.9429512   2.03343093]
 [ 2.81967672 -2.30987087]]



array([[-0.9429512 ,  2.03343093],
       [ 2.81967672, -2.30987087]])

In [147]:
# Inverse
tensor.inverse()

# Moore Pensore inverse
tensor.pinverse()

RuntimeError: "inverse_cpu" not implemented for 'Long'

In [ ]:

# .T -->> .t


# save to disk 

In [153]:
np.save('file.npy', arrayB)
print(np.load('file.npy'))
print()

torch.save(tensor, 'file')
torch.load('file')

[[3 5]
 [9 6]]



tensor([[3, 5],
        [9, 6]])

Pushing Tensor to GPU

In [155]:
# GPU - GPU - GPU 
 
# put the tensor in GPU memory
gpu_tensor = tensor.gpu()


AttributeError: 'Tensor' object has no attribute 'gpu'

### It has been firmly established that my_tensor.detach().numpy() is the correct way to get a numpy array from a torch tensor.

In [156]:
# example of :: 

import torch

tensor1 = torch.tensor([1.0,2.0],requires_grad=True)

print(tensor1)
print(type(tensor1))

tensor1 = tensor1.numpy()

print(tensor1)
print(type(tensor1))

tensor([1., 2.], requires_grad=True)
<class 'torch.Tensor'>


RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.

# hmmm
<hr/>

In [193]:
z = torch.rand(6,6)
z

tensor([[0.8404, 0.7639, 0.0902, 0.4825, 0.1496, 0.5981],
        [0.2975, 0.2805, 0.2829, 0.1401, 0.6771, 0.9271],
        [0.0611, 0.6418, 0.4665, 0.6780, 0.7632, 0.8623],
        [0.1961, 0.9288, 0.0702, 0.3197, 0.1305, 0.7733],
        [0.9573, 0.5512, 0.0855, 0.6979, 0.4054, 0.9351],
        [0.9669, 0.3596, 0.7659, 0.2990, 0.9194, 0.6028]])

In [205]:
x = torch.rand(3, 6)
x

tensor([[0.9221, 0.4891, 0.4774, 0.3212, 0.0734, 0.8755],
        [0.3208, 0.4746, 0.8845, 0.1458, 0.1844, 0.2435],
        [0.2949, 0.6163, 0.2646, 0.8587, 0.2331, 0.7830]])

In [206]:
y = torch.rand(6, 3)
y

tensor([[0.0557, 0.5316, 0.7521],
        [0.6133, 0.7051, 0.1803],
        [0.3104, 0.5547, 0.9914],
        [0.5686, 0.3296, 0.1579],
        [0.1501, 0.3423, 0.7954],
        [0.0459, 0.0166, 0.5550]])

In [207]:
x @ y

tensor([[0.7333, 1.2454, 1.8499],
        [0.7052, 1.1110, 1.5085],
        [1.0357, 1.1139, 1.3507]])

In [213]:
y @ x

tensor([[0.4436, 0.7430, 0.6958, 0.7412, 0.2774, 0.7670],
        [0.8449, 0.7457, 0.9642, 0.4546, 0.2171, 0.8498],
        [0.7564, 1.0261, 0.9011, 1.0318, 0.3562, 1.1830],
        [0.6766, 0.5319, 0.6048, 0.3662, 0.1393, 0.7017],
        [0.4827, 0.7260, 0.5848, 0.7811, 0.2595, 0.8375],
        [0.2113, 0.3724, 0.1834, 0.4938, 0.1358, 0.4788]])

In [208]:
z @ z

tensor([[1.7551, 1.6598, 0.8388, 1.0111, 1.3852, 2.1620],
        [1.9228, 1.3243, 1.0160, 1.1692, 1.5956, 1.9824],
        [1.9682, 1.8867, 1.1781, 1.4430, 1.9905, 2.7917],
        [1.3807, 1.1024, 0.9391, 0.6968, 1.5174, 1.8742],
        [2.4028, 2.1487, 1.0821, 1.3827, 1.6969, 2.6398],
        [2.4878, 2.3322, 1.1076, 1.9536, 1.9386, 3.0263]])

In [209]:
x @ z

tensor([[1.9293, 1.8016, 1.1437, 1.2527, 1.7101, 2.2613],
        [0.9053, 1.2704, 0.7883, 1.0691, 1.3621, 1.8265],
        [1.5959, 1.7755, 1.0043, 1.0793, 1.5897, 2.3298]])

In [211]:
z @ y

tensor([[0.8675, 1.2556, 1.3863],
        [0.5003, 0.8062, 1.6301],
        [1.0815, 1.2428, 1.8169],
        [0.8392, 0.9610, 0.9680],
        [0.9185, 1.3294, 1.8558],
        [0.8477, 1.6156, 2.6643]])

In [212]:
y @ z 

RuntimeError: mat1 and mat2 shapes cannot be multiplied (6x3 and 6x6)

In [204]:
x * z

tensor([[4.4559e-02, 9.5710e-02, 4.8506e-02, 4.2534e-01, 2.8464e-02, 4.2416e-01],
        [1.9747e-01, 8.0404e-02, 4.7484e-02, 1.1626e-01, 1.1018e-01, 4.0006e-01],
        [5.2353e-02, 1.6081e-01, 1.2538e-01, 3.4107e-01, 3.8891e-01, 7.0909e-01],
        [3.5879e-02, 7.9387e-01, 2.8016e-04, 3.0249e-01, 1.1095e-01, 5.4137e-01],
        [8.4944e-01, 1.1106e-01, 3.4088e-02, 3.0035e-01, 2.4377e-01, 7.4134e-01],
        [3.5706e-02, 3.3269e-01, 2.5290e-01, 1.1460e-01, 5.3896e-01, 3.1266e-01]])