# Pytorch - Numpy Learning
## Torch 
<hr/>

In [5]:
# libraries

import torch
import numpy as np 


In [6]:
# numpy 

zeros  = np.zeros((4, 4))
print(zeros)
print()
ones   = np.ones((4, 4))
print(ones)
print()
random = np.random.random((4, 4))
print(random)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[0.14887185 0.95428828 0.59857653 0.55084052]
 [0.60630747 0.50475587 0.31937092 0.91098533]
 [0.77664692 0.35098037 0.60243575 0.66483577]
 [0.38545354 0.19234342 0.99574159 0.47441368]]


In [8]:
# Pytorch

zeros  = torch.zeros(4, 4)
print(zeros)
print()
ones   = torch.ones(4, 4)
print(ones)
print()
random = torch.rand(4, 4)
print(random)


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

tensor([[0.4890, 0.9963, 0.9758, 0.7537],
        [0.5785, 0.6230, 0.0869, 0.4775],
        [0.9793, 0.6736, 0.9017, 0.1821],
        [0.5539, 0.7993, 0.8924, 0.5812]])


# Play 

In [10]:
tensor = torch.rand(4, 4)
tensor

tensor([[0.4165, 0.7103, 0.1388, 0.9000],
        [0.1043, 0.8800, 0.2302, 0.7211],
        [0.7789, 0.1815, 0.1703, 0.9412],
        [0.5113, 0.1861, 0.5624, 0.2353]])

In [38]:
tensor = torch.tensor([[3,5],[9,6]])
tensor

tensor([[3, 5],
        [9, 6]])

In [24]:
# create an arary 

arrayB = np.array([[ 3 , 5 ], [9, 6]])
arrayB

array([[3, 5],
       [9, 6]])

In [42]:
81 / (3 * 9)

3.0

In [44]:
54 / 6

9.0

In [49]:
30

42

In [ ]:
         
  

      [3, 5]   [3, 9]T  =  
      [9, 6]   [5, 6]


In [53]:
arrayB 

array([[3, 5],
       [9, 6]])

# Matrix multiplication  - recreate in 3D graphic - 

In [52]:
#Matrix multiplication  - recreate in 3D graphic - 

arrayB @ arrayB.T

array([[ 34,  57],
       [ 57, 117]])

In [48]:
# elemnt wise

arrayB * arrayB

array([[ 9, 25],
       [81, 36]])

In [54]:

# Revisit numpy ladder challenge  - > apply to torch.  -> Watch Linear Regression


In [58]:
torchA = torch.tensor([[1, 2,],[ 3, 4]]) 
torchB = torch.tensor([[11,12],[13, 14]])

In [100]:
a = torch.tensor([3,5]) 
b = torch.tensor([9,6])

In [106]:
m = torch.tensor([7,5,8]) 
j = torch.tensor([3,9,6])

In [61]:
torchA

tensor([[1, 2],
        [3, 4]])

In [62]:
torchB

tensor([[11, 12],
        [13, 14]])

In [101]:
torchA @ torchB

tensor([[37, 40],
        [85, 92]])

In [68]:
3*4 + 1 *2

14

In [ ]:
[1, 2]    [11, 12]                      [11, 13] T
[3, 4]    [13, 14]                      [12, 14] 

In [ ]:
x1, y1    m1, j1
x2, y2    m2, j2    = 

In [69]:
torchB.shape

torch.Size([2, 2])

In [70]:
torchB.size()

torch.Size([2, 2])

In [72]:
torchB.dim()

2

In [103]:
a

tensor([3, 5])

In [104]:
b

tensor([9, 6])

##  dot product =  Scalor Product  

In [115]:
print(m)
j

tensor([7, 5, 8])


tensor([3, 9, 6])

In [118]:
m @ j

tensor(114)

In [ ]:

[x1, y1] [x2, y2] =   (x1 * x2) + (y1 * y1) 
                         3 * 9 + 5 * 6
                               57

In [110]:
m @ j #  [x1, y1, z1] * [x1, y1, z1]

tensor(114)

In [ ]:
"""

what does the dot product represent in light?

dot =  a "scalar"  not a vector

|a| × |b| × cos(θ) = |a| × cos(θ) × |b|

cos(90) = 0


OR


But what is |a|:
|a| = √(4^2 + 8^2 + 10^2) 

hypotenuse 


"""

In [111]:
#  DOT product :: 
#                   a · b = |a| × |b| × cos(θ) 
   a
#                   a · b = ax × bx + ay × by


a @ b # dot product 

tensor(57)

## cross product = Vector product 

In [117]:
m * j

tensor([21, 45, 48])

In [ ]:
"""
a × b = |a| |b| sin(θ) n


    cx = aybz − azby
    cy = azbx − axbz
    cz = axby − aybx	

"""

---

In [130]:
arrayB

array([[3, 5],
       [9, 6]])

In [127]:
arrayC =  np.array( [[1,1,1],[2,2,2]] )
arrayC

array([[1, 1, 1],
       [2, 2, 2]])

In [140]:
arrayD = arrayB @ arrayC
arrayD

array([[13, 13, 13],
       [21, 21, 21]])

In [137]:
# Dot product 

"""

[3, 5]       [1  [2
[9, 6]        1   2
              1], 2]
              
          
"""

'\n\n[3, 5]   [1  [2\n[9, 6]    1   2\n          1], 2]\n'

In [ ]:
# shape 

In [31]:
# shape and dimentions 

num_dim = array.ndim
num_dim

2

In [33]:
shape = array.shape 
shape

(2, 2)

In [75]:
arrayB

array([[3, 5],
       [9, 6]])

In [83]:
arrayB.reshape((2,2))

array([[3, 5],
       [9, 6]])

In [86]:
torchB.view((2,2))

tensor([[11, 12],
        [13, 14]])

## Determinant

In [ ]:
# -0-0-0-0-0- 

In [90]:
np.linalg.det(arrayB)

-27.0

## Inverse and moore-pensore inverse

In [91]:
# inverse

np.linalg.inv(arrayB)

array([[-0.22222222,  0.18518519],
       [ 0.33333333, -0.11111111]])

In [92]:
# moore Pensore inverse

np.linalg.pinv(arrayB)

array([[-0.22222222,  0.18518519],
       [ 0.33333333, -0.11111111]])

In [ ]:
Inverse and Moore-Pensore inverse

Numpy:

# Inverse
np.linalg.inv(array)

# Moore Pensore inverse
np.linalg.pinv(array)
