# Pytorch  Learning
<hr/>

In [5]:
# libraries

import torch
import numpy as np 


In [6]:
# numpy 

zeros  = np.zeros((4, 4))
print(zeros)
print()
ones   = np.ones((4, 4))
print(ones)
print()
random = np.random.random((4, 4))
print(random)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[0.14887185 0.95428828 0.59857653 0.55084052]
 [0.60630747 0.50475587 0.31937092 0.91098533]
 [0.77664692 0.35098037 0.60243575 0.66483577]
 [0.38545354 0.19234342 0.99574159 0.47441368]]


In [8]:
# Pytorch

zeros  = torch.zeros(4, 4)
print(zeros)
print()
ones   = torch.ones(4, 4)
print(ones)
print()
random = torch.rand(4, 4)
print(random)


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

tensor([[0.4890, 0.9963, 0.9758, 0.7537],
        [0.5785, 0.6230, 0.0869, 0.4775],
        [0.9793, 0.6736, 0.9017, 0.1821],
        [0.5539, 0.7993, 0.8924, 0.5812]])
