In [8]:
import numpy as np
import torch 

In [7]:
q = np.array([5,7,8,-2,7])
q

array([ 5,  7,  8, -2,  7])

In [10]:
e = torch.tensor([5,7,8,-2,7])
e

tensor([ 5,  7,  8, -2,  7])

In [6]:
k = np.arange(2,7)
k

array([2, 3, 4, 5, 6])

In [11]:
f = torch.arange(2,7)
f

tensor([2, 3, 4, 5, 6])

In [ ]:
# slicing is the name

In [13]:
e > 0

tensor([ True,  True,  True, False,  True])

In [14]:
e[ e>0 ]

tensor([5, 7, 8, 7])

In [16]:
np.sum(q >0)

4

In [17]:
torch.sum(e > 0)

tensor(4)

In [19]:
e [e % 2 == 0]

tensor([ 8, -2])

In [22]:
e [ (e % 2 == 0) & (e > 0) ]

tensor([8])